### ISSUE TITLE
Building doesn't work

### ISSUE THREAD

**Issue by CzrCraft** [synthels/daphne#5]
The setup.sh file doesn't work. I got rid of most of the errors, by removing the second [ or ] where it was present, but i have an error at line 3.
This is the error:
/tools/setup.sh: 3: Bad substitution
Also, when i run the script it creates a build directory outside the daphne folder.

**Comment by synthels** [comment]
You need to set the default shell to bash. It's probably set to dash by default. Otherwise, run all the shell scripts like this:
`bash script_name.sh args`
not like
`./script_name.sh args`

**Comment by synthels** [comment]
And please don't edit the shell scripts, the brackets are there for a reason :)
